apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: backend-role
rules:
- apiGroups: [""] 
  resourceNames: ["api"]
  resources: ["pods","services","deployments","jobs"] 
  verbs: ["get", "watch", "list"]