apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
  name: data-analyst-role
  namespace: production
rules:
- apiGroups: [""] 
  resourceNames: ["postgres"]
  resources: ["pods"] 
  verbs: ["get", "watch", "list"]