apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: devops-role
rules:
- apiGroups: [""] 
  resourceNames: ["frontend", "api", "postgres"]
  resources: ["services","deployments","jobs"] 
  verbs: ["get", "watch", "list"]