apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontends
  namespace: development
subjects:
- kind: User
  name: vishwa 
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: ClusterRole
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontends
  namespace: staging
subjects:
- kind: User
  name: vishwa 
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: ClusterRole
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontends
  namespace: production
subjects:
- kind: User
  name: vishwa 
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: ClusterRole
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io