kubectl apply -f fe-role.yaml
kubectl apply -f fe-binding.yaml
kubectl apply -f be-role.yaml
kubectl apply -f be-binding.yaml
kubectl apply -f jfs-role.yaml
kubectl apply -f jfs-binding.yaml
kubectl apply -f da-role.yaml
kubectl apply -f da-binding.yaml
kubectl apply -f devops-role.yaml
kubectl apply -f devops-binding.yaml