apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
  name: junior-fs-dev-role
  namespace: development
rules:
- apiGroups: [""] 
  resources: ["pods","services","namespaces","deployments","jobs","nodes"] 
  verbs: ["get", "watch", "list"]