apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
  name: junior-fs-dev-role
  namespace: development
rules:
- apiGroups: [""] 
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] 
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]