apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
    {{- range $key, $value := .Values.env }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}

