{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1 
metadata:
  name: api-policy
spec:
  podSelector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress: 
    {{- if not .Values.networkPolicy.ingress.allowExternal }}
    - from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
    {{- end }}
{{- end }}
