version: "3.8"
services:
  db:
    container_name: db
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
  web:
    container_name: server
    build: ./api
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5000:8081"
    depends_on:
      - db
    restart: on-failure
