version: "3.8"
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: https://api-service:5000/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api-service
    networks:
      - ireview-app
  
  
  database:
    container_name: database
    build: ./db
    environment:
       POSTGRES_USER: postgresadmin
       POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    restart: always

    networks:
      - ireview-app
  
  api-service:
    container_name: api-service
    build: ./api
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgresadmin:admin123@database:5432/postgres
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      FRONTEND_PORT: '1234'
    ports:
      - "5000:4000"
    depends_on:
      - database
    networks:
      - ireview-app

networks:
  ireview-app:
