version: "3.8"
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_PORT: "5000"
    ports:
      - "1234:80"
    depends_on:
      - api
    restart: on-failure
  database:
    container_name: database
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    restart: always

    networks:
      - ireview-app
  
  api:
    container_name: api
    build: ./api
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:password@database:3306/test
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      FRONTEND_PORT: '1234'
    ports:
      - "5000:8081"
    depends_on:
      - database
    networks:
      - ireview-app

networks:
  ireview-app:
