version: "3.8"
services:
  database:
    container_name: database
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    restart: always

    networks:
      - ireview-app
  # web:
  #   container_name: server
  #   build: ./frontend
  #   ports:
  #     - "8181:8181"
  #   depends_on:
  #     - db
  #     - api
  #   restart: on-failure
  #   networks:
  #    - ireview-app
  
  api:
    container_name: api
    build: ./api
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:password@database:3306/test
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
    ports:
      - "5000:8081"
    depends_on:
      - database
    networks:
      - ireview-app

networks:
  ireview-app:
