{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1 
metadata:
  name: frontend-policy
spec:
  podSelector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress: 
    - ports:
        - protocol: {{ .Values.client.protocol }}
          port: {{ .Values.client.port }}
      {{- if .Values.networkPolicy.ingress.allowHTTP }}
        - protocol: {{ .Values.client.protocol }}
          port: 80
      {{- end }}
      {{- if not .Values.networkPolicy.ingress.allowExternal }}
    - from:
        - namespaceSelector:
            matchLabels:
              app: {{ .Release.Namespace }}
      {{- end }}
  egress: 
  - to: 
    - ipBlock: 
        cidr: 0.0.0.0/0 
        except: 
        - 10.116.0.0/14 
        - 10.120.0.0/20
{{- end }}
