{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1 
metadata:
  name: postgres-policy
spec:
  podSelector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress 
  ingress: 
    {{- if not .Values.networkPolicy.ingress.allowExternal }}
    - from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
    {{- end }}
      ports:
        - port: {{ .Values.service.port }}
  egress: 
  - to: 
    - ipBlock: 
        cidr: 0.0.0.0/0 
        except: 
        - 10.116.0.0/14 
        - 10.120.0.0/20
{{- end }}
