apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    app: frontend
data:
  web.properties: | 
    {{- range $key, $value := .Values.env }}
      window.{{ $key }} = "{{ $value }}"; console.log("test 3")
    {{- end }}