apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - protocol: TCP
     port: 5050
     targetPort: 443
     nodePort: {{ .Values.service.port }}
  selector:
    {{- include "frontend-chart.selectorLabels" . | nindent 4 }}