apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
   - protocol: {{ .Values.client.protocol }}
     port: 5050 
     targetPort: {{ .Values.client.port }}
     nodePort: {{ .Values.service.port }}
  selector:
    {{- include "frontend-chart.selectorLabels" . | nindent 4 }}