apiVersion: v1
kind: Service
metadata:
     name: api-service
     labels:
          app: api
spec:
     type: NodePort
     ports:
      - port: 5000
        nodePort: 30002
     selector:
      app: api