apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment 
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-deployment-container
        image: dedder98/sc:rating-frontend
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: frontend-config
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: "/usr/share/nginx/html/config.js"
            subPath: "config.js"
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: web-config
            items:
              - key: "web.properties"
                path: "config.js"