apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 5050
     targetPort: 80
     nodePort: 32001
  selector:
    app: frontend