apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment 
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-deployment-container
        image: vishwamishra/frontend:latest
        imagePullPolicy: Always
        volumeMounts:
          #override config.js file
          - name: config
            mountPath: "/usr/share/nginx/html/config.js"
            subPath: "config.js"
        ports:
          - containerPort: 80
      volumes:
        - name: config
          configMap:
              name: frontend-config
              items:
                  - key: "web.properties"
                    path: "config.js"