name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-api:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api

    steps:
    - uses: actions/checkout@v2
    - name: Docker Image for API
      run: docker build . --file Dockerfile --tag api:latest
  
  build-web:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/frontend

    steps:
    - uses: actions/checkout@v2
    - name: Docker image for web
      run: docker build . --file Dockerfile --tag frontend:latest

  build-db:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/db

    steps:
    - uses: actions/checkout@v2
    - name: Docker image for DB
      run: docker build . --file Dockerfile --tag db:latest
